apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: echo-server
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./charts/echo-server
      sourceRef:
        kind: GitRepository
        namespace: echo-server
        name: gitrepository-dhlebnikov1
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    replicaCount: 2
    image:
      tag: 0.4.0
