apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: echo-server
spec:
  interval: 1m0s
  chart:
    spec:
      path: charts/echo-server
      sourceRef:
        kind: GitRepository
        namespace: echo-server
      interval: 1m
  values:
    replicaCount: 2
    image:
      tag: 0.4.0
